{
  "id": "CVE-2021-41271",
  "package_name": "discourse",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:discourse:discourse:2.8.0:beta5:*:*:*:*:*:*",
    "cpe:2.3:a:discourse:discourse:2.8.0:beta6:*:*:*:*:*:*",
    "cpe:2.3:a:discourse:discourse:2.8.0:beta7:*:*:*:*:*:*",
    "cpe:2.3:a:discourse:discourse:*:*:*:*:*:*:*:*",
    "cpe:2.3:a:discourse:discourse:2.8.0:beta1:*:*:*:*:*:*",
    "cpe:2.3:a:discourse:discourse:2.8.0:beta2:*:*:*:*:*:*",
    "cpe:2.3:a:discourse:discourse:2.8.0:beta3:*:*:*:*:*:*",
    "cpe:2.3:a:discourse:discourse:2.8.0:beta4:*:*:*:*:*:*"
  ],
  "version_constraint": "<= 2.7.9 || = 2.8.0 || = 2.8.0 || = 2.8.0 || = 2.8.0 || = 2.8.0 || = 2.8.0 || = 2.8.0",
  "fixed_in_versions": "null",
  "severity": "Medium",
  "description": "Discourse is a platform for community discussion. In affected versions a maliciously crafted request could cause an error response to be cached by intermediate proxies. This could cause a loss of confidentiality for some content. This issue is patched in the latest stable, beta and tests-passed versions of Discourse.",
  "urls": [
    "https://github.com/discourse/discourse/commit/2da0001965c6d8632d723c46ea5df9f22a1a23f1",
    "https://github.com/discourse/discourse/security/advisories/GHSA-hf6r-mc9j-hf4p"
  ]
}
