{
  "schema_version": "1.5.0",
  "id": "BIT-2021-22200",
  "details": "An issue has been discovered in GitLab CE/EE affecting all versions starting with 12.6. Under a special condition it was possible to access data of an internal repository through a public project fork as an anonymous user.",
  "aliases": [
    "CVE-2021-22200"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "bitnami",
        "name": "gitlab",
        "purl": "pkg:bitnami/gitlab"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
        }
      ],
      "versions": [
        "13.10.0"
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "12.6.0"
            },
            {
              "fixed": "13.8.7"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "13.9.0"
            },
            {
              "fixed": "13.9.5"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "High",
    "cpes": [
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:13.10.0:*:*:*:community:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:13.10.0:*:*:*:enterprise:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22200.json"
    },
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/247523"
    }
  ],
  "published": "2023-09-04T16:07:51.559Z",
  "modified": "2023-09-04T16:11:27.534Z"
}