{
  "schema_version": "1.5.0",
  "id": "CVE-2020-13310",
  "details": "A vulnerability was discovered in GitLab runner versions before 13.1.3, 13.2.3 and 13.3.1. It was possible to make the gitlab-runner process crash by sending malformed queries, resulting in a denial of service.",
  "aliases": [
    "CVE-2020-13310"
  ],
  "affected": [
    {
      "packages": [
        {
          "ecosystem": "bitnami",
          "name": "gitlab",
          "purl": "pkg:bitnami/gitlab"
        }
      ],
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "13.1.3"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "13.2.0"
            },
            {
              "fixed": "13.2.3"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "13.3.0"
            },
            {
              "fixed": "13.3.1"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Medium",
    "cpes": [
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13310.json"
    },
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/gitlab-runner/-/issues/25857"
    },
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26819"
    }
  ],
  "published": "2023-05-31T06:37:50.912Z",
  "modified": "2023-05-31T06:37:50.912Z"
}