{
  "id": "CVE-2020-13328",
  "package_name": "gitlab",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
  ],
  "version_constraint": ">= 12.0.0, < 12.10.13 || >= 13.0.0, < 13.0.8 || >= 13.1.0, < 13.1.2",
  "fixed_in_versions": "null",
  "severity": "Medium",
  "description": "An issue has been discovered in GitLab affecting versions prior to 13.1.2, 13.0.8 and 12.10.13. GitLab was vulnerable to a stored XSS by using the PyPi files API.",
  "urls": [
    "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13328.json",
    "https://gitlab.com/gitlab-org/gitlab/-/issues/215640"
  ]
}
