{
  "schema_version": "1.5.0",
  "id": "BIT-tensorflow-2021-37671",
  "details": "TensorFlow is an end-to-end open source platform for machine learning. In affected versions an attacker can cause undefined behavior via binding a reference to null pointer in `tf.raw_ops.Map*` and `tf.raw_ops.OrderedMap*` operations. The [implementation](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/core/kernels/map_stage_op.cc#L222-L248) has a check in place to ensure that `indices` is in ascending order, but does not check that `indices` is not empty. We have patched the issue in GitHub commit 532f5c5a547126c634fefd43bbad1dc6417678ac. The fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.",
  "aliases": [
    "CVE-2021-37671"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Bitnami",
        "name": "tensorflow",
        "purl": "pkg:bitnami/tensorflow"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "2.3.0"
            },
            {
              "fixed": "2.3.4"
            },
            {
              "introduced": "2.4.0"
            },
            {
              "fixed": "2.4.3"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "2.5.0"
            },
            {
              "last_affected": "2.5.0"
            },
            {
              "introduced": "2.6.0-rc0"
            },
            {
              "last_affected": "2.6.0-rc0"
            },
            {
              "introduced": "2.6.0-rc1"
            },
            {
              "last_affected": "2.6.0-rc1"
            },
            {
              "introduced": "2.6.0-rc2"
            },
            {
              "last_affected": "2.6.0-rc2"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "High",
    "cpes": [
      "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:google:tensorflow:2.5.0:*:*:*:*:*:*:*",
      "cpe:2.3:a:google:tensorflow:2.6.0:rc0:*:*:*:*:*:*",
      "cpe:2.3:a:google:tensorflow:2.6.0:rc1:*:*:*:*:*:*",
      "cpe:2.3:a:google:tensorflow:2.6.0:rc2:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/tensorflow/tensorflow/commit/532f5c5a547126c634fefd43bbad1dc6417678ac"
    },
    {
      "type": "WEB",
      "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-qr82-2c78-4m8h"
    }
  ],
  "published": "2023-11-06T09:11:40.541Z",
  "modified": "2023-11-07T16:28:29.749Z"
}