{
  "id": "CVE-2022-40897",
  "package_name": "setuptools",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:python:setuptools:*:*:*:*:*:*:*:*"
  ],
  "version_constraint": "< 65.5.1",
  "fixed_in_versions": "null",
  "severity": "Medium",
  "description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
  "urls": [
    "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
    "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
    "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
    "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
    "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
    "https://security.netapp.com/advisory/ntap-20230214-0001/"
  ]
}
