{
  "schema_version": "1.5.0",
  "id": "BIT-2021-25287",
  "details": "An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds read in J2kDecode, in j2ku_graya_la.",
  "aliases": [
    "CVE-2021-25287"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "bitnami",
        "name": "pillow",
        "purl": "pkg:bitnami/pillow"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "8.2.0"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Critical",
    "cpes": [
      "cpe:2.3:a:python:pillow:*:*:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/pull/5377#issuecomment-833821470"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
    },
    {
      "type": "WEB",
      "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-25287-cve-2021-25288-fix-oob-read-in-jpeg2kdecode"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/202107-33"
    }
  ],
  "published": "2023-09-14T13:42:59.675Z",
  "modified": "2023-09-14T13:50:47.856Z"
}