{
  "schema_version": "1.5.0",
  "id": "BIT-2021-28378",
  "details": "Gitea 1.12.x and 1.13.x before 1.13.4 allows XSS via certain issue data in some situations.",
  "aliases": [
    "CVE-2021-28378"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "bitnami",
        "name": "gitea",
        "purl": "pkg:bitnami/gitea"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "1.12.0"
            },
            {
              "fixed": "1.12.6"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "1.13.0"
            },
            {
              "fixed": "1.13.4"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Medium",
    "cpes": [
      "cpe:2.3:a:gitea:gitea:*:*:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://blog.gitea.io/2021/03/gitea-1.13.4-is-released/"
    },
    {
      "type": "WEB",
      "url": "https://github.com/PandatiX/CVE-2021-28378"
    },
    {
      "type": "WEB",
      "url": "https://github.com/go-gitea/gitea/pull/14898"
    }
  ],
  "published": "2023-09-04T15:39:30.407Z",
  "modified": "2023-09-04T16:11:27.534Z"
}